/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as SignUpIndexImport } from './routes/sign-up/index'
import { Route as PostsIndexImport } from './routes/posts/index'
import { Route as AboutIndexImport } from './routes/about/index'
import { Route as AboutAboutImport } from './routes/about/$about'

// Create/Update Routes

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const SignUpIndexRoute = SignUpIndexImport.update({
  id: '/sign-up/',
  path: '/sign-up/',
  getParentRoute: () => rootRoute,
} as any)

const PostsIndexRoute = PostsIndexImport.update({
  id: '/posts/',
  path: '/posts/',
  getParentRoute: () => rootRoute,
} as any)

const AboutIndexRoute = AboutIndexImport.update({
  id: '/about/',
  path: '/about/',
  getParentRoute: () => rootRoute,
} as any)

const AboutAboutRoute = AboutAboutImport.update({
  id: '/about/$about',
  path: '/about/$about',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/about/$about': {
      id: '/about/$about'
      path: '/about/$about'
      fullPath: '/about/$about'
      preLoaderRoute: typeof AboutAboutImport
      parentRoute: typeof rootRoute
    }
    '/about/': {
      id: '/about/'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutIndexImport
      parentRoute: typeof rootRoute
    }
    '/posts/': {
      id: '/posts/'
      path: '/posts'
      fullPath: '/posts'
      preLoaderRoute: typeof PostsIndexImport
      parentRoute: typeof rootRoute
    }
    '/sign-up/': {
      id: '/sign-up/'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof SignUpIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about/$about': typeof AboutAboutRoute
  '/about': typeof AboutIndexRoute
  '/posts': typeof PostsIndexRoute
  '/sign-up': typeof SignUpIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about/$about': typeof AboutAboutRoute
  '/about': typeof AboutIndexRoute
  '/posts': typeof PostsIndexRoute
  '/sign-up': typeof SignUpIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/about/$about': typeof AboutAboutRoute
  '/about/': typeof AboutIndexRoute
  '/posts/': typeof PostsIndexRoute
  '/sign-up/': typeof SignUpIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/about/$about' | '/about' | '/posts' | '/sign-up'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/about/$about' | '/about' | '/posts' | '/sign-up'
  id: '__root__' | '/' | '/about/$about' | '/about/' | '/posts/' | '/sign-up/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutAboutRoute: typeof AboutAboutRoute
  AboutIndexRoute: typeof AboutIndexRoute
  PostsIndexRoute: typeof PostsIndexRoute
  SignUpIndexRoute: typeof SignUpIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutAboutRoute: AboutAboutRoute,
  AboutIndexRoute: AboutIndexRoute,
  PostsIndexRoute: PostsIndexRoute,
  SignUpIndexRoute: SignUpIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/about/$about",
        "/about/",
        "/posts/",
        "/sign-up/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/about/$about": {
      "filePath": "about/$about.tsx"
    },
    "/about/": {
      "filePath": "about/index.tsx"
    },
    "/posts/": {
      "filePath": "posts/index.tsx"
    },
    "/sign-up/": {
      "filePath": "sign-up/index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
